version: '3.8'

services:
  db:
    image: postgres:16
    restart: unless-stopped
    # volumes:
      # - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    networks:
      - backend

  base:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.base
    image: base
    depends_on:
      - db

  library-build:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.build
    image: library-build
    depends_on:
      - base


  book-mngt:
    build:
      context: ./
      dockerfile: ./apps/book-mngt/Dockerfile
    ports:
      - "4203:4203"
    depends_on:
      - db
      - library-db
    env_file: ./apps/book-mngt/.env.docker
    networks:
      - backend

  library-db:
    build:
      context: ./
      dockerfile: ./apps/borrow-mngt/Dockerfile
    ports:
      - "4202:4202"
    depends_on:
      - db
      - library-db
      - member-mngt
      - book-mngt
    env_file: ./apps/borrow-mngt/.env.docker
    networks:
      - backend

  api-gateway:
    build:
      context: ./
      dockerfile: ./apps/api-gateway/Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - member-mngt
      - book-mngt
      - borrow-mngt
    env_file: ./apps/api-gateway/.env.docker
    networks:
      - backend
      # - frontend

  # frontend:
  #   build:
  #     context: ./
  #     dockerfile: ./apps/frontend/Dockerfile
  #   ports:
  #     - "5173:80"
  #   depends_on:
  #     - api-gateway
  #   environment:
  #     - REACT_APP_LIBRARY_API_URL=api-gateway:4200
  #   args:
  #     - REACT_APP_LIBRARY_API_URL=api-gateway:4200
  #   networks:
  #     - frontend

networks:
  backend:
    driver: bridge
  # frontend:
